#consultas sql jugador
sql.insert.createNewUserRegistro= INSERT INTO Jugadores (Correo, Nombre_y_apellidos, Fecha_de_nacimiento, Contraseña) VALUES (?,?,?,?)
sql.update.updateFechaInscripcion= UPDATE Jugadores SET Fecha_de_inscripcion=? WHERE Correo=?
sql.select.requestUserInicioSesion= SELECT * FROM Jugadores WHERE Correo = ? AND Contraseña = ?
sql.update.updateDatos= UPDATE Jugadores SET Nombre_y_apellidos=?, Contraseña=?, Fecha_de_nacimiento=? WHERE Correo=?
sql.select.requestAllClients= SELECT Correo, Nombre_y_apellidos, Fecha_de_inscripcion FROM Jugadores WHERE Administrador = false

#consultas sql pista
sql.insert.createPista= INSERT INTO Pistas (Nombre, Estado, Tipo, Tamaño, Jugadores_maximos) VALUES (?,?,?,?,?)
sql.insert.createNewMaterial= INSERT INTO Materiales (Uso, Tipo, Estado) VALUES (?,?,?)
sql.select.requestMaterialesDisponibles= SELECT * FROM Materiales WHERE Estado = "DISPONIBLE"
sql.update.assignNewMaterialToPista= UPDATE Materiales SET Estado=?, Pista=? WHERE Id=?
sql.select.requestPista= SELECT * FROM Pistas WHERE Nombre= ?
sql.select.requestMaterial= SELECT * FROM Materiales WHERE Id= ?
sql.select.requestAllPistas= SELECT * FROM Pistas
sql.update.updateEstadoPista=UPDATE Pistas SET Estado = ? WHERE Nombre = ?
sql.select.requestTipoPista=SELECT * FROM Pistas WHERE Tipo = ? AND Estado = true
sql.select.requestPistasDisponiblesTamañoJugadoresInfantil= SELECT Nombre FROM Pistas WHERE Estado = true AND Tamaño = "MINIBASKET" AND Jugadores_maximos >= ?
sql.select.requestPistasDisponiblesTamañoJugadoresFamiliar= SELECT Nombre FROM Pistas WHERE Estado = true AND (Tamaño = "MINIBASKET" OR Tamaño = "TRESVSTRES") AND Jugadores_maximos >= ?
sql.select.requestPistasDisponiblesTamañoJugadoresAdultos= SELECT Nombre FROM Pistas WHERE Estado = true AND Tamaño = "ADULTOS" AND Jugadores_maximos >= ?
sql.select.checkMaxJugadoresPista= SELECT Nombre FROM Pistas WHERE Nombre = ? AND Jugadores_maximos >= ?
sql.select.requestFechaPista= SELECT * FROM Pistas p WHERE p.Estado = true AND p.Nombre NOT IN ( SELECT r.Nombre_pista FROM Reservas r WHERE DATE(r.Fecha) = ?) 
sql.update.updateEstadoMaterial= UPDATE Materiales SET Estado=? WHERE Id=?
sql.select.requestMaterialesNoReservado= SELECT * FROM Materiales WHERE Estado != "RESERVADO"
sql.select.checkDisponibilidadPista= SELECT Tipo FROM Materiales WHERE Pista = ?

#consultas sql reservas 
sql.update.modificarReserva1= UPDATE Reservas SET Fecha = ?, Hora = ?, Duracion = ?, Precio = ?, Numero_de_niños = ?, Numero_de_adultos = ? WHERE Nombre_pista = ? AND Fecha = ? AND Hora = ?
sql.update.modificarReserva2= UPDATE Reserva_Bonos SET Fecha = ?, Hora = ? WHERE Nombre_pista = ? AND Fecha = ? AND Hora = ?
sql.delete.cancelarReserva1= DELETE FROM Reservas WHERE Nombre_pista = ? AND Fecha = ? AND Hora = ?
sql.select.cancelarReserva= SELECT * FROM Reserva_Bonos WHERE Nombre_pista = ? AND Fecha = ? AND Hora = ?
sql.delete.cancelarReserva2= DELETE FROM Reserva_Bonos WHERE Nombre_pista = ? AND Fecha = ? AND Hora = ?
sql.update.cancelarReserva= UPDATE Bonos SET Sesiones_disponibles = Sesiones_disponibles + 1 WHERE Id = ?
sql.insert.createNewBono= INSERT INTO Bonos (Correo_usuario, Tipo, Sesiones_disponibles) VALUES (?,?,5)
sql.insert.createReservaIndividual= INSERT INTO Reservas (Correo_usuario, Nombre_pista, Fecha, Hora, Duracion, Numero_de_adultos, Numero_de_niños, Descuento, Precio ) VALUES (?,?,?,?,?,?,?,?,?)
sql.insert.createAñadirReservaABono1= INSERT INTO Reserva_Bonos (Id_bono, Nombre_pista, Fecha, Hora) VALUES (?,?,?,?)
sql.insert.createAñadirReservaABono2= INSERT INTO Reservas (Correo_usuario, Nombre_pista, Fecha, Hora, Duracion, Numero_de_adultos, Numero_de_niños, Descuento, Precio ) VALUES (?,?,?,?,?,?,?,?,?)
sql.update.createAñadirReservaABono= UPDATE Bonos SET Sesiones_disponibles = Sesiones_disponibles - 1, Fecha_caducidad = CASE WHEN Fecha_caducidad IS NULL THEN ? ELSE Fecha_caducidad END WHERE Id = ?
sql.select.requestReservasCancelable= SELECT * FROM Reservas WHERE Correo_usuario = ? AND STR_TO_DATE(CONCAT(Fecha, ' ', Hora), '%Y-%m-%d %H:%i:%s') > NOW() + INTERVAL 24 HOUR
sql.select.requestProximaReserva= SELECT Fecha FROM Reservas WHERE Correo_usuario=? AND Fecha > ? ORDER BY Fecha ASC LIMIT 1
sql.select.requestNumeroReservas= SELECT Fecha FROM Reservas WHERE Correo_usuario=? AND Fecha < ? 
sql.select.requestReservasFuturas= SELECT Fecha, Hora, Nombre_pista, Correo_usuario, Duracion FROM Reservas WHERE Fecha > ?
sql.select.requestReservasEntreFechas= SELECT Correo_usuario, Nombre_pista, Fecha, Hora, Duracion, Numero_de_adultos, Numero_de_niños FROM Reservas WHERE Correo_usuario = ? AND Fecha <= ? AND Fecha >= ? 
sql.select.checkBonoTipoReservaInfantil= SELECT Id FROM Bonos WHERE Correo_usuario = ? AND Sesiones_disponibles != 0 AND (Fecha_caducidad > ? OR Fecha_caducidad is null) AND Tipo = "MINIBASKET"
sql.select.checkBonoTipoReservaFamiliar= SELECT Id FROM Bonos WHERE Correo_usuario = ? AND Sesiones_disponibles != 0 AND (Fecha_caducidad > ? OR Fecha_caducidad is null) AND (Tipo = "MINIBASKET" OR Tipo = "TRESVSTRES")
sql.select.checkBonoTipoReservaAdultos= SELECT Id FROM Bonos WHERE Correo_usuario = ? AND Sesiones_disponibles != 0 AND (Fecha_caducidad > ? OR Fecha_caducidad is null) AND Tipo = "ADULTOS"
sql.select.checkDisponibilidadPista2= SELECT Fecha, Hora, Duracion FROM Reservas WHERE Nombre_pista = ?
sql.select.requestReservasFuturasCorreo= SELECT Fecha, Hora, Nombre_pista, Duracion, Descuento, Numero_de_niños, Numero_de_adultos FROM Reservas WHERE Fecha > ? AND Correo_usuario = ?
